Fp generator prototype
Boranadas/rdkit pull request #1
Opened 2018-05-28 07:50 UTC by Boranadas

Prototype for fingerprint generator

2018-05-28 08:05 UTC, Boranadas commented
@greglandrum @NadineSchneider @AndreaVolkamer 
How does this structure look compared to the ideas we talked about? I will update this PR based on your feedback.

2018-05-28 08:11 UTC, Boranadas commented on Code/GraphMol/Fingerprints/FingerprintGenerator.h
> +        //extra return
We can store extra outputs and return them with methods.

2018-05-28 08:12 UTC, Boranadas commented on Code/GraphMol/Fingerprints/FingerprintGenerator.h
> +
These would return null if not applicable for the fp type

2018-05-28 15:45 UTC, greglandrum requested changes
I think you're going in the right direction.
There are some small suggestions here and a couple of larger ones.

2018-05-28 15:45 UTC, greglandrum commented on Code/GraphMol/Fingerprints/FingerprintGenerator.h
> +#include <DataStructs/SparseIntVect.h>
Please put all includes inside the `#ifndef` guard

2018-05-28 15:45 UTC, greglandrum commented on Code/GraphMol/Fingerprints/FingerprintGenerator.h
> +#ifndef _RD_FINGERPRINTGEN_H_
Please don't start or end the `#define` with underscore characters (there are a lot of places in the RDKit that still do this, but they shouldn't).
Use something like `RD_FINGERPRINTGEN_H_2018_05`

2018-05-28 15:45 UTC, greglandrum commented on Code/GraphMol/Fingerprints/FingerprintGenerator.h
> +        //extra return
unfortunately, I think this doesn't work because it will make the methods non-threadsafe. I think we're going to need to do these calculations and return the values inside the fingerprinting methods themselves.

2018-05-28 15:45 UTC, greglandrum commented on Code/GraphMol/Fingerprints/FingerprintGenerator.h
> +        SparseIntVect<boost::int32_t> *getFingerPrint(const ROMol &mol);
I think the return values for some of the methods here are wrong. Certainly the arguments (required arguments) are. Should think about which return type corresponds to which function.

Each of these methods should also be declared to be const (because they shouldn't change the underlying object)

2018-05-28 23:05 UTC, Boranadas commented on Code/GraphMol/Fingerprints/FingerprintGenerator.h
> +      const AdditionalOutput *additionalOutput = 0) const;
Rest of the arguments would be held in the class, so the method only has molecule dependent arguments. I am not sure about the return types. Every method has an explicit bit vector returning version.

2018-05-28 23:08 UTC, Boranadas commented on Code/GraphMol/Fingerprints/FingerprintGenerator.h
> +      const AdditionalOutput *additionalOutput = 0) const;
Does it make sense to skip having this method and keeping whether to use count simulation in the class as well?

2018-05-29 03:07 UTC, greglandrum commented on Code/GraphMol/Fingerprints/FingerprintGenerator.h
> +      const AdditionalOutput *additionalOutput = 0) const;
good point, that makes sense to me

2018-05-29 03:11 UTC, greglandrum commented on Code/GraphMol/Fingerprints/FingerprintGenerator.h
> +  SparseIntVect<boost::uint32_t> *getHashedFingerprint(
I think it's worth considering changing the name of this to `getFoldedFingerprint()` 
I think that the use of the word 'hashed` in the current API is confusing since all fingerprints use a hashing function. We might as well go ahead and fix that now.

`getHashedFingerprintAsBitVect()` would also need to be renamed.

2018-05-29 03:18 UTC, greglandrum commented on Code/GraphMol/Fingerprints/FingerprintGenerator.h
> +      const AdditionalOutput *additionalOutput = 0) const;
Ok, I agree with the rest of the arguments being configuration that shows up in the class.

2018-05-29 03:27 UTC, greglandrum commented on Code/GraphMol/Fingerprints/FingerprintGenerator.h
> + public:
Suggested method renaming and return types:

- `SparseIntVect<boost::uint32_t> *getFingerprintAsCounts()`
- `SparseIntVect<boost::uint32_t> *getFoldedFingerprintAsCounts()`
- `SparseBitVect *getFingerprintAsCounts()`
- `ExplicitBitVect *getFoldedFingerprintAsBitVect()`

We should consider having the return type of `getFoldedFingerprintAsCounts()` be a `DiscreteValueVect` because that's more explicit and is likely to be more efficient.

2018-05-29 14:52 UTC, Boranadas commented on Code/GraphMol/Fingerprints/FingerprintGenerator.h
> +}
Bits set for each atom might be a common output but would it be meaningful output for all types of fıingerprints?

2018-05-29 14:55 UTC, greglandrum commented on Code/GraphMol/Fingerprints/FingerprintGenerator.h
> +}
I think it's probably meaningful. There's a question about whether or not it's useful, but that's a different story. :-)

2018-05-29 14:57 UTC, Boranadas commented on Code/GraphMol/Fingerprints/FingerprintGenerator.h
> + public:
Another possible way to approach this would be to have different methods for constructing and returning different types of output (SparseIntVect, SparseBitVect, ExplicitBitVect, DiscreteValueVect) and letting the user pick the best for the use case. Folding also would be a part of the class configuration. However, I am not sure how this would affect implementation or if it would over complicate things.

2018-05-29 15:50 UTC, greglandrum commented on Code/GraphMol/Fingerprints/FingerprintGenerator.h
> + public:
I'm not sure I understand, but it may not be important.
The problem is that the type of the result is generally determined by the nature of the function being called. For example, and unfolded fingerprint does not fit in an ExplicitBitVect or DiscreteValueVect.

2018-05-31 14:41 UTC, Boranadas commented
@greglandrum during the meeting we talked about merging this as is and moving on then changing the API over time as necessary. I think working on the implementation will help shape the API from my perspective. What do you think?

2018-05-31 16:11 UTC, greglandrum commented
yes, makes sense to me

2018-05-31 16:37 UTC, merged